### ISSUE TITLE
WLI not support for currencyCode=INR

### ISSUE THREAD

**Issue by aguspuryanto** [wl-online-payments-direct/sdk-php#10]
hi, i try this WLI sdk, but not support for currencyCode=INR

Input validation error: - UNKNOWN_PRODUCT_ID(1007)

**Comment by worldline-direct-support-team** [comment]
Hello @aguspuryanto,

Thank you for reaching out to us and sharing the information regarding the issue you are
facing. We appreciate your diligence in bringing this to our attention.

Upon further investigation, it appears that the issue you are encountering is related to
the API rather than the SDK itself. To ensure you receive the best possible support for
this issue, we kindly suggest submitting a request through our [Contact Form](https://docs.direct.worldline-solutions.com/en/about/contact/) on our Documentation portal. Our support team is readily available to assist you in resolving the issue and answer any questions you may have specifically related to the API.

If you encounter any issues specifically related to the SDK, we are more than happy to
provide you with assistance as well. We appreciate your feedback and apologise for any
inconvenience this issue may have caused.

Kind regards,
Worldline Online Payments Support Team
