### ISSUE TITLE
unit test in project used wl-online-payments-direct

### ISSUE THREAD

**Issue by medabaied** [wl-online-payments-direct/sdk-php#4]
Hello,

I try add unit test for my project when I use wl-online-payments-direct but I found this error when I extend ClientTestCase class

Warning:       XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set

Testing 
...E................                                              20 / 20 (100%)

Time: 00:00.169, Memory: 16.00 MB

There was 1 error:

1) App\Tests\Unit\PaymentServiceTest::testApproveAndDeposit
Error: Class 'OnlinePayments\Sdk\ClientTestCase' not found

/var/www/tests/Unit/PaymentServiceTest.php:38

code :

`use OnlinePayments\Sdk\ClientTestCase;

class PaymentServiceTest extends ClientTestCase
{
   }
`

**Comment by worldline-direct-support-team** [comment]
Hello mabaied,

Thank you for reporting an issue. 
We will have a look into this.

Kind regards,
Worldline Support

**Comment by worldline-direct-support-team** [comment]
Hey @medabaied 

The issue here is with the composer autoloader.

The Class ‘OnlinePayments\Sdk\ClientTestCase' is registered in the wl-online-payments-direct composer in the "autoload-dev" section and if you load it in your project’s compose.json like:

...
"require": {
  ...
  "wl-online-payments-direct/sdk-php": "^5.17"
}
...

it won’t autoload the classes from the "autoload-dev" section.

There are many possible workarounds, we suggest one of the two:

Using composer: In your project’s compose.json file add:

{
  ...
  "autoload-dev": {
    "psr-4": {
      "OnlinePayments\\Sdk\\": "vendor/wl-online-payments-direct/sdk-php/tests/OnlinePayments/Sdk"
    }
  }
  ...
}

This will ensure that the classes from the test directory of the wl-online-payments-direct library are loaded

Manually load the class in your test

You can directly include the file containing the ClientTestCase class in your test:

require_once __DIR__ . '/../vendor/wl-online-payments-direct/sdk-php/tests/path/to/ClientTestCase.php';

use OnlinePayments\Sdk\ClientTestCase;

class MyTest extends ClientTestCase
{
    // Your test code
}

Let us know if you have any other questions.
